### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by fzdy-zz**
Alpine缺少wget 添加方便自定义shell

### CODE REVIEW

**Comment by iouAkira** [comment]
@fzdy-zz 现在wget不可用？截图看看，我一直用的好好的

**Comment by fzdy-zz** [comment]
> @fzdy-zz 现在wget不可用？截图看看，我一直用的好好的

/scripts # wget https://raw.githubusercontent.com/shylocks/Loon/main/jd_gyec.js                                                                   
Connecting to raw.githubusercontent.com (199.232.68.133:443)                                                                                      
wget: error getting response: Connection reset by peer                                                                                            
/scripts #

**Comment by iouAkira** [comment]
@fzdy-zz Connection reset by peer                                                                                     这个是你网络问题，跟wget包没关系啊

**Comment by fzdy-zz** [comment]
> @fzdy-zz Connection reset by peer 这个是你网络问题，跟wget包没关系啊

apk add wget之后
/scripts # wget wget https://raw.githubusercontent.com/shylocks/Loon/main/jd_gyec.js                                                              
                                                                                                  
--2021-01-17 12:40:38--  https://raw.githubusercontent.com/shylocks/Loon/main/jd_gyec.js                                                          
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.68.133                                                                 
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.68.133|:443... connected.                                             
HTTP request sent, awaiting response... 200 OK                                                                                                    
Length: 34548 (34K) [text/plain]                                                                                                                  
Saving to: 'jd_gyec.js'                                                                                                                         
                                                                                                                                                  
jd_gyec.js                        100%[====================================================================>]  33.74K  2.88KB/s    in 12s      
                                                                                                                                                  
2021-01-17 12:40:54 (2.88 KB/s) - 'jd_gyec.js' saved [34548/34548]                                                                              
                                                                                                                                                  
FINISHED --2021-01-17 12:40:54--                                                                                                                  
Total wall clock time: 16s                                                                                                                        
Downloaded: 1 files, 34K in 12s (2.88 KB/s)

**Comment by iouAkira** [comment]
@fzdy-zz Connection reset by peer                                                                                        字面意思没啥可争论的，你别add wget 试试 加个raw的hosts看看是不是wget不可用

**Comment by fzdy-zz** [comment]
> @fzdy-zz Connection reset by peer 字面意思没啥可争论的，你别add wget 试试 加个raw的hosts看看是不是wget不可用

cat myhost
# GitHub Start
140.82.112.4 github.com
140.82.114.3 gist.github.com
185.199.108.153 assets-cdn.github.com
199.232.68.133 raw.githubusercontent.com
199.232.68.133 gist.githubusercontent.com
199.232.68.133 cloud.githubusercontent.com
199.232.68.133 camo.githubusercontent.com
199.232.68.133 avatars0.githubusercontent.com
199.232.68.133 avatars1.githubusercontent.com
199.232.68.133 avatars2.githubusercontent.com
199.232.68.133 avatars3.githubusercontent.com
199.232.68.133 avatars4.githubusercontent.com
199.232.68.133 avatars5.githubusercontent.com
199.232.68.133 avatars6.githubusercontent.com
199.232.68.133 avatars7.githubusercontent.com
199.232.68.133 avatars8.githubusercontent.com
# GitHub End

/scripts #                                                                                                                                        
/scripts #                                                                                                                                        
/scripts # wget https://raw.githubusercontent.com/shylocks/Loon/main/jd_gyec.js                                                                   
Connecting to raw.githubusercontent.com (199.232.68.133:443)                                                                                      
wget: error getting response: Connection reset by peer                                                                                            
/scripts #                                                                                                                                        
/scripts #                                                                                                                                        
/scripts # apk add wget                                                                                                                           
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz                                                                     
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz                                                                
(1/3) Installing libunistring (0.9.10-r0)                                                                                                         
(2/3) Installing libidn2 (2.3.0-r0)                                                                                                               
(3/3) Installing wget (1.21.1-r1)                                                                                                                 
Executing busybox-1.32.1-r0.trigger                                                                                                               
OK: 127 MiB in 42 packages                                                                                                                        
/scripts # wget https://raw.githubusercontent.com/shylocks/Loon/main/jd_gyec.js                                                                   
--2021-01-17 12:52:20--  https://raw.githubusercontent.com/shylocks/Loon/main/jd_gyec.js                                                          
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.68.133                                                                 
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.68.133|:443... connected.                                             
HTTP request sent, awaiting response... 200 OK                                                                                                    
Length: 34548 (34K) [text/plain]                                                                                                                  
Saving to: 'jd_gyec.js'                                                                                                                           
                                                                                                                                                  
jd_gyec.js                           100%[====================================================================>]  33.74K  18.8KB/s    in 1.8s     
                                                                                                                                                  
2021-01-17 12:52:23 (18.8 KB/s) - 'jd_gyec.js' saved [34548/34548]                                                                                
                                                                                                                                                  
/scripts #                                                                                                                                        
/scripts #

**Comment by iouAkira** [comment]
你这是docker容器里面的hosts ？

**Comment by fzdy-zz** [comment]
> 你这是docker容器里面的hosts ？

软路由里的自定义hosts

**Comment by iouAkira** [comment]
> > 你这是docker容器里面的hosts ？
> 
> 软路由里的自定义hosts

软路由里面定义了啥hosts跟容器没关系吧，我意思你的在容器里面加

**Comment by fzdy-zz** [comment]
> > > 你这是docker容器里面的hosts ？
> > 
> > 
> > 软路由里的自定义hosts
> 
> 软路由里面定义了啥hosts跟容器没关系吧，我意思你的在容器里面加

一会我试下，我换组Ip看看

**Comment by iouAkira** [comment]
image
image
image

**Comment by fzdy-zz** [comment]
> > > > 你这是docker容器里面的hosts ？
> > > 
> > > 
> > > 软路由里的自定义hosts
> > 
> > 
> > 软路由里面定义了啥hosts跟容器没关系吧，我意思你的在容器里面加
> 
> 一会我试下，我换组Ip看看

容器内HOSTS修改第一次
===================
/scripts #                                                                                                                                      
/scripts #                                                                                                                                      
/scripts # cat /etc/hosts                                                                                                                       
127.0.0.1       localhost                                                                                                                       
::1     localhost ip6-localhost ip6-loopback                                                                                                    
fe00::0 ip6-localnet                                                                                                                            
ff00::0 ip6-mcastprefix                                                                                                                         
ff02::1 ip6-allnodes                                                                                                                            
ff02::2 ip6-allrouters                                                                                                                          
172.17.0.4      jd_scripts-test      
127.0.0.1       localhost 
                                                           
                                                                                                                                                
#GitHub Start                                                                                                                                   
140.82.112.4 github.com                                                                                                                         
140.82.114.3 gist.github.com                                                                                                                    
185.199.108.153 assets-cdn.github.com                                                                                                           
13.229.188.59 raw.githubusercontent.com                                                                                                         
13.229.188.59 gist.githubusercontent.com                                                                                                        
13.229.188.59 cloud.githubusercontent.com                                                                                                       
13.229.188.59 camo.githubusercontent.com                                                                                                        
13.229.188.59 avatars0.githubusercontent.com                                                                                                    
13.229.188.59 avatars1.githubusercontent.com                                                                                                    
13.229.188.59 avatars2.githubusercontent.com                                                                                                    
13.229.188.59 avatars3.githubusercontent.com                                                                                                    
13.229.188.59 avatars4.githubusercontent.com                                                                                                    
13.229.188.59 avatars5.githubusercontent.com                                                                                                    
13.229.188.59 avatars6.githubusercontent.com                                                                                                    
13.229.188.59 avatars7.githubusercontent.com                                                                                                    
13.229.188.59 avatars8.githubusercontent.com                                                                                                    
                                                                                                                                                
#GitHub End                                                                                                                                     
                                                                                                                                                
                                                                                                                                                
/scripts # wget https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_bookshop.js                                                      
Connecting to raw.githubusercontent.com (13.229.188.59:443)                                                                                     
wget: error getting response: Connection reset by peer                                                                                          
/scripts #     



容器内HOSTS修改第二次
===================
/scripts #                                                                                                                                      
/scripts #                                                                                                                                      
/scripts #                                                                                                                                      
/scripts # cat /etc/hosts                                                                                                                       
127.0.0.1       localhost                                                                                                                       
::1     localhost ip6-localhost ip6-loopback                                                                                                    
fe00::0 ip6-localnet                                                                                                                            
ff00::0 ip6-mcastprefix                                                                                                                         
ff02::1 ip6-allnodes                                                                                                                            
ff02::2 ip6-allrouters                                                                                                                          
172.17.0.4      jd_scripts-test      
127.0.0.1       localhost 
                                                                                                                                                
#GitHub Start                                                                                                                                   
140.82.112.4 github.com                                                                                                                         
140.82.114.3 gist.github.com                                                                                                                    
185.199.108.153 assets-cdn.github.com                                                                                                           
151.101.228.133 raw.githubusercontent.com                                                                                                         
151.101.228.133 gist.githubusercontent.com                                                                                                        
151.101.228.133 cloud.githubusercontent.com                                                                                                       
151.101.228.133 camo.githubusercontent.com                                                                                                        
151.101.228.133 avatars0.githubusercontent.com                                                                                                    
151.101.228.133 avatars1.githubusercontent.com                                                                                                    
151.101.228.133 avatars2.githubusercontent.com                                                                                                    
151.101.228.133 avatars3.githubusercontent.com                                                                                                    
151.101.228.133 avatars4.githubusercontent.com                                                                                                    
151.101.228.133 avatars5.githubusercontent.com                                                                                                    
151.101.228.133 avatars6.githubusercontent.com                                                                                                    
151.101.228.133 avatars7.githubusercontent.com                                                                                                    
151.101.228.133 avatars8.githubusercontent.com                                                                                                    
                                                                                                                                                
#GitHub End                                                                                                                                     
                                                                                                                                                
/scripts #
/scripts #                                                                                                                                                
/scripts # wget https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_bookshop.js                                                      
Connecting to raw.githubusercontent.com (151.101.228.133:443)                                                                                     
wget: error getting response: Connection reset by peer                                                                                          
/scripts #          
/scripts #                                                                                                                                      
/scripts # wget https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_bookshop.js                                                      
Connecting to raw.githubusercontent.com (151.101.228.133:443)                                                                                   
wget: error getting response: Connection reset by peer                                                                                          
/scripts #              
/scripts # wget https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_bookshop.js                                                      
Connecting to raw.githubusercontent.com (151.101.228.133:443)                                                                                   
wget: error getting response: Connection reset by peer                                                                                          
/scripts # apk add wget                                                                                                                         
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz                                                                   
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz                                                              
(1/3) Installing libunistring (0.9.10-r0)                                                                                                       
(2/3) Installing libidn2 (2.3.0-r0)                                                                                                             
(3/3) Installing wget (1.21.1-r1)                                                                                                               
Executing busybox-1.32.1-r0.trigger                                                                                                             
OK: 127 MiB in 42 packages                                                                                                                      
                                                                                                                    
/scripts # wget https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_bookshop.js                                                      
--2021-01-17 20:07:08--  https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_bookshop.js                                             
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.228.133                                                              
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.228.133|:443... connected.                                          
Unable to establish SSL connection.                                                                                                             
/scripts #            


===================================================
算了不折腾了，群晖就这德行，导入后手动apk add wget一下,能用就行。

**Pull request closed without merging**
